# Generated by Django 5.2.1 on 2025-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
