# Generated by Django 5.2.1 on 2025-06-07 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'location')},
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='branch',
            name='business',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
    ]
