# Generated by Django 5.2.1 on 2025-06-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_unique_together_branch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='service',
            name='business',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('business', 'name', 'location')},
        ),
    ]
