# Generated by Django 5.2.1 on 2025-06-19 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_expense_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseNameSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_name_suggestions', to='core.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_suggestions', to='core.expensecategory')),
            ],
            options={
                'unique_together': {('business', 'category', 'name')},
            },
        ),
    ]
