# Generated by Django 5.2.1 on 2025-06-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expensenamesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='core.business'),
            preserve_default=False,
        ),
    ]
