# Generated by Django 5.2.1 on 2025-06-09 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_unique_together_remove_service_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.branch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'branch', 'role')},
            },
        ),
        migrations.DeleteModel(
            name='UserBusinessRole',
        ),
    ]
