# Generated by Django 5.2.1 on 2025-06-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Amount paid so far for this transaction (for partial payments).', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid'), ('pending', 'Not Paid / Pending')], default='pending', help_text='Tracks if the transaction is fully paid, partially paid, or pending.', max_length=20),
        ),
    ]
