# Generated by Django 5.2.1 on 2025-06-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_party_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseNameSuggestion',
        ),
    ]
