# Generated by Django 5.2.1 on 2025-06-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branchemployee_delete_userbusinessrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_services',
        ),
        migrations.RemoveField(
            model_name='visitservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='visitservice',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='visitservice',
            name='visit',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.branch')),
            ],
            options={
                'unique_together': {('branch', 'name', 'type')},
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_items',
            field=models.ManyToManyField(blank=True, to='core.item'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='VisitService',
        ),
    ]
