# Generated by Django 5.2.1 on 2025-06-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='core.item'),
        ),
    ]
