# Generated by Django 5.2.1 on 2025-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_cost_price_alter_item_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='business',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business',
        ),
        migrations.AddField(
            model_name='branchemployee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchemployee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchemployee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
