# Generated by Django 5.2.1 on 2025-06-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
