# Generated by Django 5.2.1 on 2025-06-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_unique_together_item_business_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
