# Generated by Django 5.2.1 on 2025-06-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_party_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='enable_loyalty_point_earning',
            field=models.BooleanField(default=True, help_text='Allow customers to earn loyalty points on purchases.'),
        ),
    ]
