# Generated by Django 5.2.1 on 2025-06-23 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesssettings_enable_loyalty_point_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Amount refunded for this transaction (if status is 'refunded').", max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded')], default='completed', help_text='Overall status of the transaction (e.g., Completed, Voided, Refunded).', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_by',
            field=models.ForeignKey(blank=True, help_text='User who voided this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
